2025-08-04 12:00:42,782 INFO    MainThread:7996 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-08-04 12:00:42,782 INFO    MainThread:7996 [wandb_setup.py:_flush():80] Configure stats pid to 7996
2025-08-04 12:00:42,782 INFO    MainThread:7996 [wandb_setup.py:_flush():80] Loading settings from C:\Users\visha\.config\wandb\settings
2025-08-04 12:00:42,783 INFO    MainThread:7996 [wandb_setup.py:_flush():80] Loading settings from C:\Users\visha\Downloads\ML_ASSIGNMENT_AYNA\wandb\settings
2025-08-04 12:00:42,783 INFO    MainThread:7996 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-04 12:00:42,783 INFO    MainThread:7996 [wandb_init.py:setup_run_log_directory():703] Logging user logs to C:\Users\visha\Downloads\ML_ASSIGNMENT_AYNA\wandb\run-20250804_120042-v644acac\logs\debug.log
2025-08-04 12:00:42,783 INFO    MainThread:7996 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to C:\Users\visha\Downloads\ML_ASSIGNMENT_AYNA\wandb\run-20250804_120042-v644acac\logs\debug-internal.log
2025-08-04 12:00:42,783 INFO    MainThread:7996 [wandb_init.py:init():830] calling init triggers
2025-08-04 12:00:42,783 INFO    MainThread:7996 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-08-04 12:00:42,783 INFO    MainThread:7996 [wandb_init.py:init():871] starting backend
2025-08-04 12:00:43,004 INFO    MainThread:7996 [wandb_init.py:init():874] sending inform_init request
2025-08-04 12:00:43,058 INFO    MainThread:7996 [wandb_init.py:init():882] backend started and connected
2025-08-04 12:00:43,059 INFO    MainThread:7996 [wandb_init.py:init():953] updated telemetry
2025-08-04 12:00:43,062 INFO    MainThread:7996 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-04 12:00:44,154 INFO    MainThread:7996 [wandb_init.py:init():1029] starting run threads in backend
2025-08-04 12:00:44,225 INFO    MainThread:7996 [wandb_run.py:_console_start():2458] atexit reg
2025-08-04 12:00:44,225 INFO    MainThread:7996 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-08-04 12:00:44,225 INFO    MainThread:7996 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-08-04 12:00:44,225 INFO    MainThread:7996 [wandb_run.py:_redirect():2398] Redirects installed.
2025-08-04 12:00:44,229 INFO    MainThread:7996 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-04 12:05:59,543 INFO    MsgRouterThr:7996 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 6 handles.
2025-08-04 12:07:23,041 ERROR   MainThread:7996 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\interface\interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 150, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-08-04 12:07:23,176 ERROR   MainThread:7996 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\interface\interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 150, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-08-04 12:07:23,177 ERROR   MainThread:7996 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\interface\interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 150, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\wandb\sdk\lib\sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
